import { Permissions, Role } from '../types/index';

export const PERMISSIONS: Record<Role, Permissions> = {
  SUPER_OWNER: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: true,
    canUseTerminal: true,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  SUPER_ADMIN: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: true,
    canUseTerminal: true,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  SUPER_ROOT: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: true,
    canUseTerminal: true,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  super_admin: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: true,
    canUseTerminal: true,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  TENANT_OWNER: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  OWNER: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  owner: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: true,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: true,
    canViewGrowth: true,
  },
  ADMIN: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  admin: {
    canEditCatalog: true,
    canViewProfits: true,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  STAFF: {
    canEditCatalog: true,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  staff: {
    canEditCatalog: true,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  FINANCE: {
    canEditCatalog: false,
    canViewProfits: true,
    canManageDomains: false,
    canViewFraud: true,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  finance: {
    canEditCatalog: false,
    canViewProfits: true,
    canManageDomains: false,
    canViewFraud: true,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  SUPPORT: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  support: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  RESELLER: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  },
  reseller: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  },
  MEMBER: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  },
  member: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  },
  SUPPLIER: {
    canEditCatalog: true,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  supplier: {
    canEditCatalog: true,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: true,
  },
  CUSTOMER: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  },
  customer: {
    canEditCatalog: false,
    canViewProfits: false,
    canManageDomains: false,
    canViewFraud: false,
    canUseTerminal: false,
    canManageSuppliers: false,
    canViewGrowth: false,
  }
};

export const MOCK_METRICS = [
  { name: '08:00', volume: 120, revenue: 4500 },
  { name: '10:00', volume: 340, revenue: 12000 },
  { name: '12:00', volume: 210, revenue: 8000 },
  { name: '14:00', volume: 560, revenue: 21000 },
  { name: '16:00', volume: 430, revenue: 15500 },
  { name: '18:00', volume: 890, revenue: 32000 },
  { name: '20:00', volume: 1100, revenue: 45000 },
];

export const MARGIN_DATA = [
  { name: 'Supplier Cost', value: 75, color: '#334155' },
  { name: 'Agency Profit', value: 15, color: '#3b82f6' },
  { name: 'Reseller Cut', value: 8, color: '#10b981' },
  { name: 'Taxes', value: 2, color: '#f59e0b' },
];

export const APP_CONFIG = {
  USE_MOCK_MODE: true, // Forced true for this development cycle
  API_FALLBACK_URL: 'https://api.mock.nexuscore.io',
  GLOBAL_LIMITS: {
    MAX_TRANSACTION_AMOUNT: 10000000, // 10 Million IDR
    MIN_TRANSACTION_AMOUNT: 1000,     // 1 Thousand IDR
    MAX_DAILY_VOLUME_PER_RESELLER: 50000000, // 50 Million IDR
  }
};
