import React from 'react';
import { Activity } from 'lucide-react';

export const Footer = () => (
  <footer className="bg-slate-950 border-t border-white/[0.04] p-2 flex justify-between items-center px-4 shrink-0">
    <div className="flex items-center gap-6">
      <div className="flex items-center gap-2">
        <Activity className="w-3 h-3 text-emerald-500" />
        <span className="text-xs text-slate-400 font-mono uppercase font-semibold italic">Network Stable</span>
      </div>
      <p className="text-xs font-mono text-slate-300 tracking-wider hidden md:block uppercase">PRD GENERATED BY NEXUS_ARCH_v1 // END_OF_LOG</p>
    </div>
    <div className="flex items-center gap-2">
      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
      <span className="text-xs text-slate-500 font-mono uppercase font-semibold">2026 NEXUSCORE LABORATORY</span>
    </div>
  </footer>
);
